//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoPayStationCommon.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class DownloadSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DownloadSettings defaultInstance = ((DownloadSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DownloadSettings())));
        
        public static DownloadSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ChunkCount {
            get {
                return ((int)(this["ChunkCount"]));
            }
            set {
                this["ChunkCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long MaxBps {
            get {
                return ((long)(this["MaxBps"]));
            }
            set {
                this["MaxBps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowParallelDownload {
            get {
                return ((bool)(this["AllowParallelDownload"]));
            }
            set {
                this["AllowParallelDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreAllocateFile {
            get {
                return ((bool)(this["PreAllocateFile"]));
            }
            set {
                this["PreAllocateFile"] = value;
            }
        }
    }
}
